import { cx } from '@/utils'
import '/styles/globals.css'
import { Montserrat, Poppins } from 'next/font/google'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

const mont = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat'
})

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins'
})

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={cx(
          mont.variable,
          poppins.variable,
          'bg-bglight dark:bg-bgdark font-poppins relative min-h-screen'
        )}
      >
        {children}
      </body>
    </html>
  )
}
